
variables:
  Major: '1'
  Minor: '0'
  Patch: 0
  BuildConfiguration: 'release'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseDotNet@2
  displayName: 'Install tools'
  inputs:
    packageType: 'sdk'
    version: 2.1.505

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: succeeded()
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Nuget Pack'
  condition: succeeded()
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: PublishPipelineArtifact@0
  condition: succeeded()
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'