# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  Major: '1'
  Minor: '0'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseDotNet@2
  displayName: 'Install tools'
  inputs:
    packageType: 'sdk'
    version: 2.1.505

- task: DotNetCoreCLI@2
  displayName: 'NuGet Restore'
  condition: succeeded()
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: succeeded()
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Nuget Pack'
  condition: succeeded()
  inputs:
    command: 'pack'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(rev:.r)'